kind: pipeline
type: docker
name: integration

steps:
  - name: build
    image: boulundeasv/dotnet-sdk-with-java
    commands:
      - dotnet sonarscanner begin /k:"easv-devops_DroneTestBalint_AY2-C89nEVvRW2O60ECr" /d:sonar.host.url="http://sonar.setgo.dk:9000" /d:sonar.token="sqp_5f4c02dcebd634251b67547b786936aeb5fa18cb"
      - - cd ./UnitTests/
      - dotnet build --no-incremental
      - dotnet sonarscanner end /d:sonar.token="sqp_5f4c02dcebd634251b67547b786936aeb5fa18cb"